#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
  CREATE USER "${DB_USER}";
  ALTER USER "${DB_USER}" WITH ENCRYPTED PASSWORD '${DB_PASS}';
  CREATE DATABASE "${DB_NAME}";
  GRANT ALL PRIVILEGES ON DATABASE "${DB_NAME}" TO "${DB_USER}";
EOSQL

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" -d "${DB_NAME}" <<-EOSQL
  SET TIME ZONE 'UTC';
  GRANT ALL ON SCHEMA public TO "${DB_USER}";
EOSQL
